# 43 แฟ้ม: HOME
COLUMNS = [
    'hospcode',
    'hid',
    'house_id',
    'housetype',
    'roomno',
    'condo',
    'house',
    'soisub',
    'soimain',
    'road',
    'villaname',
    'village',
    'tambon',
    'ampur',
    'changwat',
    'telephone',
    'latitude',
    'longitude',
    'nfamily',
    'locatype',
    'vhvid',
    'headid',
    'toilet',
    'water',
    'watertype',
    'garbage',
    'housing',
    'durability',
    'cleanliness',
    'ventilation',
    'light',
    'watertm',
    'mfood',
    'bcontrol',
    'acontrol',
    'chemical',
    'outdate',
    'd_update',
]

SQL = """
SELECT
  COALESCE((SELECT hospitalcode FROM opdconfig LIMIT 1), '') AS hospcode,
  COALESCE(CAST(h.house_id AS CHAR), '') AS hid,
  COALESCE(CAST(h.house_id AS CHAR), '') AS house_id,
  COALESCE(CAST(h.house_type_id AS CHAR), '') AS housetype,
  '' AS roomno, '' AS condo,
  COALESCE(h.address, '') AS house,
  '' AS soisub, '' AS soimain, COALESCE(h.road, '') AS road,
  '' AS villaname,
  COALESCE(LPAD(h.village_id, 2, '0'), '') AS village,
  '' AS tambon, '' AS ampur, '' AS changwat,
  '' AS telephone,
  COALESCE(h.latitude, '') AS latitude,
  COALESCE(h.longitude, '') AS longitude,
  '' AS nfamily, '' AS locatype, '' AS vhvid, '' AS headid,
  '' AS toilet, '' AS water, '' AS watertype, '' AS garbage,
  '' AS housing, '' AS durability, '' AS cleanliness, '' AS ventilation,
  '' AS light, '' AS watertm, '' AS mfood, '' AS bcontrol,
  '' AS acontrol, '' AS chemical, '' AS outdate,
  COALESCE(DATE_FORMAT(h.last_update, '%%Y%%m%%d%%H%%i%%s'), '') AS d_update
FROM house h
WHERE h.house_id IS NOT NULL
  AND %s <= %s AND %s = %s
"""
