# 43 แฟ้ม: VILLAGE
COLUMNS = [
    'hospcode',
    'vid',
    'ntraditional',
    'nmonk',
    'nreligionleader',
    'nbroadcast',
    'nradio',
    'npchc',
    'nclinic',
    'ndrugstore',
    'nchildcenter',
    'npschool',
    'nsschool',
    'ntemple',
    'nreligiousplace',
    'nmarket',
    'nshop',
    'nfoodshop',
    'nstall',
    'nraintank',
    'nchickenfarm',
    'npigfarm',
    'wastewater',
    'garbage',
    'nfactory',
    'latitude',
    'longitude',
    'outdate',
    'numactually',
    'risktype',
    'numstateless',
    'nexerciseclub',
    'nolderlyclub',
    'ndisableclub',
    'nnumberoneclub',
    'd_update',
]

SQL = """
SELECT '' AS hospcode, '' AS vid, '' AS ntraditional, '' AS nmonk, '' AS nreligionleader,
       '' AS nbroadcast, '' AS nradio, '' AS npchc, '' AS nclinic, '' AS ndrugstore,
       '' AS nchildcenter, '' AS npschool, '' AS nsschool, '' AS ntemple, '' AS nreligiousplace,
       '' AS nmarket, '' AS nshop, '' AS nfoodshop, '' AS nstall, '' AS nraintank,
       '' AS nchickenfarm, '' AS npigfarm, '' AS wastewater, '' AS garbage, '' AS nfactory,
       '' AS latitude, '' AS longitude, '' AS outdate, '' AS numactually, '' AS risktype,
       '' AS numstateless, '' AS nexerciseclub, '' AS nolderlyclub, '' AS ndisableclub,
       '' AS nnumberoneclub, '' AS d_update
FROM dual WHERE 1=0 AND %s='' AND %s='' AND %s='' AND %s=''
"""
